import json

import pytest

from klanex import WebhookVerificationError, sign_webhook, verify_webhook

# Golden vector generated by the engine's Go implementation
# (internal/webhook.Sign) — proves cross-language compatibility.
GO_SECRET = "whsec_crosslang_test"
GO_TS = 1700000000
GO_BODY = '{"event":"execution.completed","execution_id":"exe_1","status":"SUCCEEDED","attempts":2}'
GO_SIGNATURE = "sha256=2ef91bb368013c9950082137fd1aefd7e3802c405c9c9cf82277883d08e5295b"


def test_sign_matches_go_implementation():
    assert sign_webhook(GO_SECRET, GO_TS, GO_BODY) == GO_SIGNATURE


def test_verify_accepts_go_signed_delivery():
    event = verify_webhook(
        secret=GO_SECRET,
        body=GO_BODY,
        signature=GO_SIGNATURE,
        timestamp=GO_TS,
        now=GO_TS + 10,
    )
    assert event.event == "execution.completed"
    assert event.execution_id == "exe_1"
    assert event.status == "SUCCEEDED"
    assert event.attempts == 2


def test_verify_accepts_bytes_body():
    event = verify_webhook(
        secret=GO_SECRET,
        body=GO_BODY.encode(),
        signature=GO_SIGNATURE,
        timestamp=GO_TS,
        now=GO_TS,
    )
    assert event.execution_id == "exe_1"


def test_verify_rejects_tampered_body():
    with pytest.raises(WebhookVerificationError, match="signature mismatch"):
        verify_webhook(
            secret=GO_SECRET,
            body=GO_BODY.replace("SUCCEEDED", "FAILED   "),
            signature=GO_SIGNATURE,
            timestamp=GO_TS,
            now=GO_TS,
        )


def test_verify_rejects_wrong_secret():
    with pytest.raises(WebhookVerificationError, match="signature mismatch"):
        verify_webhook(
            secret="whsec_wrong",
            body=GO_BODY,
            signature=GO_SIGNATURE,
            timestamp=GO_TS,
            now=GO_TS,
        )


def test_verify_rejects_stale_timestamp():
    with pytest.raises(WebhookVerificationError, match="tolerance"):
        verify_webhook(
            secret=GO_SECRET,
            body=GO_BODY,
            signature=GO_SIGNATURE,
            timestamp=GO_TS,
            now=GO_TS + 301,
        )


def test_verify_tolerance_can_be_disabled():
    event = verify_webhook(
        secret=GO_SECRET,
        body=GO_BODY,
        signature=GO_SIGNATURE,
        timestamp=GO_TS,
        now=GO_TS + 999_999,
        tolerance_seconds=0,
    )
    assert event.execution_id == "exe_1"


def test_verify_rejects_garbage_timestamp():
    with pytest.raises(WebhookVerificationError, match="invalid timestamp"):
        verify_webhook(
            secret=GO_SECRET, body=GO_BODY, signature=GO_SIGNATURE, timestamp="nope"
        )


def test_verify_parses_error_events_with_llm_hint():
    body = json.dumps(
        {
            "event": "execution.failed",
            "execution_id": "exe_2",
            "status": "FAILED",
            "attempts": 1,
            "error": {
                "code": "TARGET_REJECTED",
                "message": "400",
                "llm_hint": "fix the payload",
            },
        }
    )
    ts = 1700000100
    event = verify_webhook(
        secret=GO_SECRET,
        body=body,
        signature=sign_webhook(GO_SECRET, ts, body),
        timestamp=ts,
        now=ts,
    )
    assert event.error is not None
    assert event.error.code == "TARGET_REJECTED"
    assert event.error.llm_hint == "fix the payload"
